import Head from 'next/head'
import KeepPages from './keepPages'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Keep Pages by DW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="col-12">

          <div className="">

            <KeepPages />

          </div>
        </div>

    </div>
  )
}
